INSERT INTO cached_suppliers (payee_id, payee_name, mastercard_business_name, city, state, category, mcc, industry, payment_type, confidence, last_updated) VALUES
('a1m3l000004L4HBAA0', 'raynham mart', '', 'Raynham', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003QVcgQAG', 're-habitat, LLC', '', 'Fayetteville', '', 'Business', '8999', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002PEA4YAO', 'reALTY TAX CONSULTANTS LLC', '', 'DALLAS', '', 'Unknown', '8931', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000006XvR6YAK', 'reQuire, LLC', '', 'Virginia Beach', '', 'Unknown', '9399', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003CnLEYA0', 'ready refresh', '', 'Louisville', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002QwReQAK', 'reallygreatmeetings, Inc.', '', 'Nokomis', '', 'Unknown', '', 'Business Services', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000004WUn6YAG', 'reflection:digital', '', 'Baltimore', '', 'Unknown', '7372', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007L2uaYAC', 'republic services', '', 'chicago', '', 'Unknown', '4900', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007L2sIYAS', 'republic services', '', 'chicago', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007L2zRYAS', 'republic services', '', 'Charlotte', '', 'Unknown', '4900', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002ayUXYAY', 'reynolds advanced materials', '', 'Broadview', '', 'Business', '5970', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LBwxAAG', 'ricky s market', '', 'Danville', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003msi0AAA', 'rio tex', '', 'Kathleen', 'Florida', '', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004fbHVQAY', 'ripple', '', 'East Canton', '', 'Business', '5399', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QeTdAAK', 'ritu beverage inc', '', 'Calvert City', '', 'Unknown', '5921', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007P3s6YAC', 'rnr tires springfield', '', 'Cincinnati', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482mhYAA', 'robledo cervantes, antonio', '', 'Stockton', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482iDYAQ', 'robles cruz, zoila', '', 'Lodi', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mpu5AAA', 'rodriguez', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004gc7RQAQ', 'roger gonzalez', '', 'Fresno', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VVGXAA4', 'romanak electric', '', 'Culver City', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003w4UCYAY', 'room 360 by FOH', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002MCXTQA4', 'room 360 by FOH', '', 'Miami', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003RtocQAC', 'row2k media', '', 'Princeton', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003rfY0YAI', 'royal business bank', '', 'San Gabriel', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002M8N7QAK', 'royal flush plumbing', '', 'SNELLVILLE', '', 'Business', '1711', 'Business Services', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007T6aoYAC', 'sComm', '', 'Raytown', '', 'Business', '5399', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mpjMAAQ', 'sabiti', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DFf8AAG', 'sad', '', 'Columbus', '', 'Unknown', '5691', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003HWbhYAG', 'salesforce.com inc.', '', 'San Francisco', '', 'Unknown', '4816', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004KvhtAAC', 'salesforce.com, inc.', '', 'Dallas', '', 'Business', '4816', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LJ4XAAW', 'sams food stores', '', 'Manchester', '', 'Unknown', '5411', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mpvzAAA', 'sanchez', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mqTvAAI', 'sanchez', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004L7QWAA0', 'sandip sindha', '', 'Porter', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kEUAQA2', 'saraechecksupplier2', '', '', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003nq9OAAQ', 'sarah sullivan', '', 'NEW YORK', '', 'Individual', '8999', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QkPmAAK', 'satkaival inc', '', 'Northlake', '', 'Unknown', '5921', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000008s3lhYAA', 'sciencemusicvideos LLC', '', 'Berkeley', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000006I93uYAC', 'scott''s printing & design', '', 'Denver', '', 'Business', '7311', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003HUNGYA4', 'scotthillDesign LLC', '', 'Marietta', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000004DcC4YAK', 'scotthillDesign LLC', '', 'Marietta', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007OFy3YAG', 'seqWell Inc', '', 'Beverly', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QeHKAA0', 'sertifi', '', 'chicago', '', 'Unknown', '7399', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003hlQaYAI', 'sertifi Inc', '', 'Chicago', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VXbcAAG', 'sfsdffafsdf', '', 'Atlanta', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004KzyuAAC', 'shailesh patel', '', 'Cleveland', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004L6h5AAC', 'sherpa express llc', '', 'Gilmer', '', 'Unknown', '5499', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003HTfTYAW', 'shoptelligence', '', 'Ann Arbor', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ0000092oDHYAY', 'showNets LLC', '', 'Peoria', '', 'Business', '4816', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QdTHAA0', 'shree keshav inc', '', 'Waynesboro', '', 'Unknown', '5921', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007OG7CYAW', 'signcovers.com', '', 'Tampa', '', 'Business', '5399', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Qhl7AAC', 'sikeston kwikshop inc', '', 'Sikeston', '', 'Unknown', '5541', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004fbwjQAA', 'sim2GROW, LLC', '', 'Beavercreek', '', 'Business', '7392', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007OCesYAG', 'simEd Holdings LLC', '', 'Westlake Village', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LBrdAAG', 'smc properties llc', '', 'Long Beach', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mn4vAAA', 'snk electric llc', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003noQ2AAI', 'socialtables', '', 'Washington', '', 'Unknown', '', 'Hospitality', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mpsOAAQ', 'song', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482e4YAA', 'soto de serrano, maria', '', 'Stockton', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482vOYAQ', 'soto felipe, trinidad', '', 'lodi', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VcQHAA0', 'southwest community church', '', 'Linesville', '', 'Unknown', '8661', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mmmeAAA', 'southwest sport surfaces, inc.', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QeH2AAK', 'specialtybottle.com', '', 'Seattle', '', 'Unknown', '5999', 'Manufacturing', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007OFvdYAG', 'sportsdepot.com', '', 'Long Beach', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004fd11QAA', 'sportsthroughthelens.com', '', 'Ballston Spa', '', 'Business', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003zpOwYAI', 'star 1', '', 'Coppell', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mqUKAAY', 'stevenson', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mpixAAA', 'stewart', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mvYnAAI', 'studio hatch, LLC', '', 'Point Richmond', '', '', '7221', 'Construction', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482cRYAQ', 'suarez ramirez, noe', '', 'lodi', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000006S3T9YAK', 'summit county Fiscal office', '', 'Akron', '', 'Tax/Government', '9399', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003CnNLYA0', 'surescripts LLC', '', 'Arlington', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mqUPAAY', 'swind', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003dPt7YAE', 'synack', '', 'Coffeyville', '', 'Unknown', '7372', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003muzFAAQ', 'terra Firma Surveys Inc', '', 'St Helena', '', '', '5499', 'Construction', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QilsAAC', 'test', '', 'dsfsf', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002JcFgYAK', 'test', '', 'Mountain View', '', 'Unknown', '8099', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LJNXAA4', 'test', '', 'test', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QiyZAAS', 'test', '', 'New York', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QiyCAAS', 'test', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002T82lYAC', 'test', '', 'Fremont', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003VrOAQA0', 'test', '', 'Portsmouth,', '', 'Unknown', '5942', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Qf77AAC', 'test', '', 'San Francisco', '', 'Unknown', '5942', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QilxAAC', 'test', '', 'sdfsf', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004krvsQAA', 'test', '', 'Orlando', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QiyPAAS', 'test', '', 'New York', '', 'Unknown', '5942', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ0000091Q99YAE', 'test', '', 'asd', '', 'Unknown', '8099', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003PZ4xQAG', 'test address vendor 3 - no 2nd address', '', 'Somersworth', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003PZ3IQAW', 'test address vendor 4 same address', '', 'Somersworth', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002uSv9YAE', 'test rate', '', '', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002uSvGYAU', 'test rate2', '', '', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VRbiAAG', 'test supplier', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VUmMAAW', 'test supplier 123', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004oLE1QAM', 'test12344', '', '', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002MDTrQAO', 'test_muzamal_2', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002MEAqQAO', 'test_muzamal_3', '', 'Miami', '', 'Unknown', '5812', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004gKySQAU', 'test_supplier_API', '', 'Miami', '', 'Unknown', '5734', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kYNVQA2', 'test_supplier_API10', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kddTQAQ', 'test_supplier_API12', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kddUQAQ', 'test_supplier_API13', '', 'Miami', '', 'Unknown', '5734', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kzqeQAA', 'test_supplier_API14', '', 'Miami', '', 'Unknown', '5734', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002QvcuQAC', 'test_supplier_API5', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kE59QAE', 'test_supplier_API6', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003PZ3bQAG', 'testaddress vendor', '', 'Wilmington,', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003PZ5GQAW', 'testaddress vendor2 - no tax info', '', 'Dover', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003nwJIAAY', 'testbn', '', 'Houston', '', 'Unknown', '5942', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QiyUAAS', 'testbn', '', 'Los Angeles', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DGJLAA4', 'testbn', '', 'Snellville', '', 'Unknown', '5942', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003nwJcAAI', 'testbn', '', 'Chicago', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DFf3AAG', 'testbn', '', 'Orlando', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003nwJeAAI', 'testbn', '', 'Norcross', '', 'Unknown', '5942', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VRygAAG', 'testbn', '', 'Houston', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DFemAAG', 'testbn', '', 'a', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004fu5LQAQ', 'testbranding', '', '', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004fu5PQAQ', 'testmigratedpartner', '', '', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003RLMSQA4', 'testrefid', '', '', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGGcAAO', 'testsupplier000', '', 'Miami', '', 'Unknown', '7399', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LKWIAA4', 'testsupplier00002', '', 'Miami', '', 'Unknown', '8099', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002MASnQAO', 'testsupplier00002', '', 'Miami', '', 'Unknown', '8099', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGfNAAW', 'testsupplier001', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGj6AAG', 'testsupplier002', '', 'Miami', '', 'Unknown', '7399', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LH1eAAG', 'testsupplier003', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGHKAA4', 'testsupplier004', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LHjdAAG', 'testsupplier004', '', 'Miami', '', 'Unknown', '7399', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LHjIAAW', 'testsupplier005', '', 'Miami', '', 'Unknown', '7399', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGcGAAW', 'testsupplier005', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LHjAAAW', 'testsupplier006', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGfpAAG', 'testsupplier006', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGd9AAG', 'testsupplier007', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LH12AAG', 'testsupplier009', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGb1AAG', 'testsupplier1000', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGZJAA4', 'testsupplier1001', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGbSAAW', 'testsupplier1002', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004KxW3AAK', 'testsupplier12', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGHVAA4', 'testsupplier234', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LGzlAAG', 'testsupplier2345', '', 'Miami', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004L3TWAA0', 'testsupplier54', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LKlxAAG', 'testsupplierbulkuploader', '', 'corporate city', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LIUlAAO', 'testsupplierexpress', '', 'Naples', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LHjcAAG', 'testsupplieridme', '', 'Miami', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000008Uv9CYAS', 'textLIVING', '', 'NASHVILLE', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ0000045Nk2YAE', 'the Tour Company Inc', '', 'Wilmington', '', 'Unknown', '7991', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003w4HoYAI', 'the Tour Company Inc', '', 'Wilmington', '', 'Business', '7991', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QhncAAC', 'the market place citgo', '', 'Milledgeville', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004kV1EQAU', 'theAgency', '', 'MILILANI', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ0000060Vq8YAE', 'theWit Hotel', '', 'Chicago', '', 'Internal Transfer', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003HUGqYAO', 'theYGSgroup', '', 'York', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QeGVAA0', 'thermalair inc', '', 'Anahelm', '', 'Unknown', '', 'Construction', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DLK6AAO', 'thyssenkrupp Elevator Corporation', '', 'ATLANTA', '', 'Unknown', '', 'Manufacturing', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003Rs5SQAS', 'thyssenkrupp Elevator Corporation', '', 'Atlanta', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003RtSnQAK', 'thyssenkrupp Elevator Corporation', '', 'Carol Stream', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DKk2AAG', 'thyssenkrupp Elevator Corporation', '', 'Carol Stream', '', 'Unknown', '', 'Manufacturing', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482uNYAQ', 'tiernan lang, eamon', '', 'elmira', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LD7LAAW', 'timeout market', '', 'Waynesville', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mpsGAAQ', 'torres', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482jBYAQ', 'torres rivera, adrian', '', 'tracy', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004L4XfAAK', 'toteabag', '', 'Balch Springs', '', 'Unknown', '5734', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004L0pSAAS', 'toteabag', '', 'Dayton', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VZXQAA4', 'travLBudi LLC', '', 'Bow', '', 'Unknown', '8999', 'Hospitality', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mitCAAQ', 'travLBudi LLC', '', 'Bow', 'New Hampshire', '', '', 'Hospitality', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mv0VAAQ', 'travel Incorporated', '', 'Columbia', '', '', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003Rx3OQAS', 'uConnect', '', 'Cambridge', '', 'Business', '', 'Business Services', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000005ubmjYAA', 'uConnect Inc', '', 'Cambridge', '', 'Unknown', '7392', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003RsSGQA0', 'uConnect Inc', '', 'Cambridge', '', 'Business', '4121', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000006XvT7YAK', 'unCommon Construction', '', 'New Orleans', '', 'Unknown', '8398', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VRMBAA4', 'uni point market', '', 'Richmond', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DGGJAA4', 'unify business solutions', '', 'Norwich', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007L2vZYAS', 'united health care', '', 'PALATINE', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000004833nYAA', 'uribe de solano, alicia', '', 'manteca', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Qf78AAC', 'user1', '', 'San Francisco', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Qf6wAAC', 'user1', '', 'San Francisco', '', 'Unknown', '7372', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000002M3YpQAK', 'v', '', 'SAN FRANSISCO', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003HWPQYA4', 'vXchnge', '', 'Philadelphia,', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000004Dc9TYAS', 'vXchnge', '', 'Philadelphia,', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004KvSeAAK', 'vXchnge-Facilities, LLC', '', 'Secaucus', '', 'Business', '7372', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000004833tYAA', 'valdes ramirez, juan manuel', '', 'Stockton', '', 'Unknown', '7299', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482yoYAA', 'valenzuela munoz, salvador', '', 'Tracy', '', 'Unknown', '7538', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482sMYAQ', 'valenzuela, luz', '', 'Stockton', '', 'Unknown', '7538', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003nenUYAQ', 'vanZelm Heywood & Shadford, Inc.', '', 'Farmington', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482fgYAA', 'vasquez del toro, yaneth', '', 'lodi', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003r3dWQAQ', 'vda Inc', '', 'East Hanover', '', 'Unknown', '742', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Qgn2AAC', 'veer enterprise inc', '', 'Jackson', '', 'Unknown', '5921', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ00000482kSYAQ', 'vega de martinez, leonor', '', 'Stockton', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000004833SYAQ', 'verdoza munoz, salvador', '', 'lodi', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000003HWp5YAG', 'verizon wireless', '', 'NEWARK', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002qbJMYAY', 'versare', '', 'Minneapolis', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mt88AAA', 'vestal & Wiler', '', 'None', 'None', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mm6dAAA', 'viDesktop Inc.', '', 'None', 'None', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003ns0UAAQ', 'viDesktop Inc.', '', 'TORONTO', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DMlnAAG', 'vickis pf warrior fund c/o Central Bank', '', 'Springfield', '', 'Unknown', '5812', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LC6KAAW', 'villa park shell', '', 'Villa Park', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mmi2AAA', 'vineyards', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DBzgAAG', 'vipVP FRESH', '', 'NOGALES', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VToRAAW', 'vishnu prithiv', '', 'Henderson', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VahqAAC', 'vishnu prithiv', '', 'texas', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VWf4AAG', 'vishnu prithiv', '', 'Henderson', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VYaZAAW', 'vishnu prithiv', '', 'Henderson', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004DN4SAAW', 'voestalpine eifeler Coatings, Inc.', '', 'Elgin', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mjLlAAI', 'von Briesen & Roper S.C.', '', 'Milwaukee', 'Wisconsin', '', '8111', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007OFipYAG', 'von Briesen & Roper s.c.', '', 'Milwaukee', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003VdevAAC', 'walkersgrocery', '', 'Whitesburg', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004wTjZQAU', 'wanderlust Content Studio, LLC', '', 'Los Angeles', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004KzyGAAS', 'way2go mart', '', 'Lafayette', '', 'Unknown', '5699', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Vd2UAAS', 'webstaurantstore.com', '', 'Lititiz', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Qf6VAAS', 'webstaurantstore.com', '', 'Lititiz', '', 'Unknown', '5046', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QeFzAAK', 'webstaurantstore.com', '', 'Lititz', '', 'Unknown', '5046', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mq3LAAQ', 'weems', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000006Ky3VYAS', 'werdmvmnt studios LLC', '', 'Cicero', '', 'Unknown', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003muZrAAI', 'wf-TOBACCO OUTLET', '', 'SAN BRUNO', '', '', '5999', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mqUtAAI', 'whelpley', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mqUwAAI', 'williams', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000007L35EYAS', 'willis driver', '', 'Anderson', '', 'Unknown', '6513', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003QhoaAAC', 'winners circle', '', 'Pulaski', '', 'Unknown', '5541', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003Vd7eAAC', 'www.club-decades.com', '', 'Los Angeles', '', 'Unknown', '', '', 'ACH', 1.0, CURRENT_TIMESTAMP),
('a1m3l000004LIR1AAO', 'x o corporation', '', 'Kansas City', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003VrayQAC', 'xxxxx', '', 'Portsmouth', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000002nueNYAQ', 'yelena yemchuk', '', 'Brooklyn', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003VpTOQA0', 'youbringfire', '', 'Phoenix', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mq0rAAA', 'young', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mv3BAAQ', 'young travel Inc', '', 'Los Angeles', '', '', '4511', 'Hospitality', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003VuZyQAK', 'yourEVOLVEDmind, LLC', '', 'Brooklyn', '', 'Business', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1mRQ000006HzMKYA0', 'zTechDeals LLC', '', 'Hortonville', '', 'Business', '5818', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m3l000003mqsrAAA', 'zunino', '', '', '', '', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000003QVhAQAW', 'zz CINTAS CORPORATION UNIFORMS', '', 'CHICAGO', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004k4YIQAY', ' Chicago White Sox', '', 'CHICAGO', '', 'Unknown', '', '', 'PrintedCheck', 1.0, CURRENT_TIMESTAMP),
('a1m6O000004oRpJQAU', 'Étude Arts LLC', '', 'New York', '', 'Business', '', '', 'Card', 1.0, CURRENT_TIMESTAMP)
ON CONFLICT (payee_id) DO UPDATE SET 
  payee_name = EXCLUDED.payee_name,
  mastercard_business_name = EXCLUDED.mastercard_business_name,
  city = EXCLUDED.city,
  state = EXCLUDED.state,
  category = EXCLUDED.category,
  mcc = EXCLUDED.mcc,
  industry = EXCLUDED.industry,
  payment_type = EXCLUDED.payment_type,
  last_updated = CURRENT_TIMESTAMP;