INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('GE CAPITAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('GE HEALTHCARE FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('GEICO', 'System', 'Government/Financial exclusion keyword', TRUE),
('GENERAL SERVICES', 'System', 'Government/Financial exclusion keyword', TRUE),
('GEORGIA POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('GM', 'System', 'Government/Financial exclusion keyword', TRUE),
('GM FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('GOVERNING BOARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('GOVERNMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('GOVERNOR', 'System', 'Government/Financial exclusion keyword', TRUE),
('GRACE PERIOD TRUST', 'System', 'Government/Financial exclusion keyword', TRUE),
('GRANT', 'System', 'Government/Financial exclusion keyword', TRUE),
('GREAT PLAINS ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('GREEN DOT BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('GUARDIAN LIFE', 'System', 'Government/Financial exclusion keyword', TRUE),
('GUSTO', 'System', 'Government/Financial exclusion keyword', TRUE),
('HARBOR', 'System', 'Government/Financial exclusion keyword', TRUE),
('HARTFORD', 'System', 'Government/Financial exclusion keyword', TRUE),
('HEALTH AND HUMAN SERVICES', 'System', 'Government/Financial exclusion keyword', TRUE),
('HEALTH BENEFIT FUND', 'System', 'Government/Financial exclusion keyword', TRUE),
('HEALTH DEPARTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('HEALTH INSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('HEALTHSPRING', 'System', 'Government/Financial exclusion keyword', TRUE),
('HIGHMARK', 'System', 'Government/Financial exclusion keyword', TRUE),
('HMRC', 'System', 'Government/Financial exclusion keyword', TRUE),
('HOLDINGS', 'System', 'Government/Financial exclusion keyword', TRUE),
('HOME EQUITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('HOMELAND SECURITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('HONDA', 'System', 'Government/Financial exclusion keyword', TRUE),
('HONDA FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('HOUSING AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('HOUSING FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('HUD', 'System', 'Government/Financial exclusion keyword', TRUE),
('HUMANA', 'System', 'Government/Financial exclusion keyword', TRUE),
('HUNTINGTON BANCSHARES', 'System', 'Government/Financial exclusion keyword', TRUE),
('HYDRO', 'System', 'Government/Financial exclusion keyword', TRUE),
('HYUNDAI', 'System', 'Government/Financial exclusion keyword', TRUE),
('IMMIGRATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('IMPORT EXPORT', 'System', 'Government/Financial exclusion keyword', TRUE),
('INDIVIDUAL ACH PAYMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('INDUSTRIAL DEVELOPMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('INDUSTRIAL RELATIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('INSPECTION', 'System', 'Government/Financial exclusion keyword', TRUE),
('INSPECTORATE', 'System', 'Government/Financial exclusion keyword', TRUE),
('INSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('INSURANCE COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('INSURER', 'System', 'Government/Financial exclusion keyword', TRUE),
('INTELLECTUAL PROPERTY', 'System', 'Government/Financial exclusion keyword', TRUE),
('INTERCOMPANY', 'System', 'Government/Financial exclusion keyword', TRUE),
('INTERNAL REVENUE', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;