INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('ACCOUNTING OFFICE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ACCOUNTS PAYABLE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ADJUDICATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('ADMINISTRATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('ADP', 'System', 'Government/Financial exclusion keyword', TRUE),
('ADVANTA', 'System', 'Government/Financial exclusion keyword', TRUE),
('AEP', 'System', 'Government/Financial exclusion keyword', TRUE),
('AETNA', 'System', 'Government/Financial exclusion keyword', TRUE),
('aflac', 'System', 'Government/Financial exclusion keyword', TRUE),
('AGENCY', 'System', 'Government/Financial exclusion keyword', TRUE),
('AGRICULTURAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('AIG', 'System', 'Government/Financial exclusion keyword', TRUE),
('alabama power', 'System', 'Government/Financial exclusion keyword', TRUE),
('alagasco', 'System', 'Government/Financial exclusion keyword', TRUE),
('ALLY', 'System', 'Government/Financial exclusion keyword', TRUE),
('ALPHERA FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('ALTRIA', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMERICAN ELECTRIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMERICAN EXPRESS', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMERICAN FAMILY', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMERIPRISE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ameris bank', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMERISURE', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMEX', 'System', 'Government/Financial exclusion keyword', TRUE),
('AMICA', 'System', 'Government/Financial exclusion keyword', TRUE),
('ANNUITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('ANTHEM', 'System', 'Government/Financial exclusion keyword', TRUE),
('ARBITRATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('archer energy', 'System', 'Government/Financial exclusion keyword', TRUE),
('ARCHIVES', 'System', 'Government/Financial exclusion keyword', TRUE),
('ARIZONA PUBLIC SERVICE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ARMY', 'System', 'Government/Financial exclusion keyword', TRUE),
('ARVEST BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('ASSET MANAGEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('ASSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ASYLUM', 'System', 'Government/Financial exclusion keyword', TRUE),
('AT & T', 'System', 'Government/Financial exclusion keyword', TRUE),
('AT&T', 'System', 'Government/Financial exclusion keyword', TRUE),
('ATT', 'System', 'Government/Financial exclusion keyword', TRUE),
('AUDIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('AURORA ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('AUSTIN ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('AVISTA', 'System', 'Government/Financial exclusion keyword', TRUE),
('AXA', 'System', 'Government/Financial exclusion keyword', TRUE),
('BANC', 'System', 'Government/Financial exclusion keyword', TRUE),
('BANC CORP', 'System', 'Government/Financial exclusion keyword', TRUE),
('BANCORP', 'System', 'Government/Financial exclusion keyword', TRUE),
('BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('Bank of', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;