INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('MELLON', 'government_excluded', TRUE),
('MEMORIAL HOSPITAL PAYROLL', 'government_excluded', TRUE),
('MERCEDES BENZ FINANCIAL', 'government_excluded', TRUE),
('merrill lynch', 'government_excluded', TRUE),
('MERS', 'government_excluded', TRUE),
('METLIFE', 'government_excluded', TRUE),
('METRO WATER', 'government_excluded', TRUE),
('MILITARY', 'government_excluded', TRUE),
('MILLIMAN BENEFITS', 'government_excluded', TRUE),
('MINING', 'government_excluded', TRUE),
('MINNESOTA POWER', 'government_excluded', TRUE),
('MIZUHO', 'government_excluded', TRUE),
('MORGAN', 'government_excluded', TRUE),
('MORGAN STANLEY', 'government_excluded', TRUE),
('MORTGAGE', 'government_excluded', TRUE),
('MORTGAGE COMPANY', 'government_excluded', TRUE),
('MORTGAGE SERVICING', 'government_excluded', TRUE),
('MOSAIC PAYMENTS', 'government_excluded', TRUE),
('MTA', 'government_excluded', TRUE),
('MUNICIPAL', 'government_excluded', TRUE),
('MUNICIPAL ELECTRIC', 'government_excluded', TRUE),
('MUNICIPAL POWER', 'government_excluded', TRUE),
('MUNICIPALITY', 'government_excluded', TRUE),
('mututal of omaha', 'government_excluded', TRUE),
('NATIONAL BANK', 'government_excluded', TRUE),
('NATIONAL FINANCE', 'government_excluded', TRUE),
('NATIONAL GRID', 'government_excluded', TRUE),
('NATIONAL TREASURY', 'government_excluded', TRUE),
('NAVY', 'government_excluded', TRUE),
('NCR', 'government_excluded', TRUE),
('NEW JERSEY UTILITIES', 'government_excluded', TRUE),
('NISSAN MOTOR ACCEPTANCE', 'government_excluded', TRUE),
('NORTHERN NATURAL GAS', 'government_excluded', TRUE),
('NORTHWESTERN MUTUAL', 'government_excluded', TRUE),
('NSTAR', 'government_excluded', TRUE),
('NUCLEAR', 'government_excluded', TRUE),
('OCCUPATIONAL SAFETY', 'government_excluded', TRUE),
('OCEAN VIEW INSURANCE', 'government_excluded', TRUE),
('OFFICE OF', 'government_excluded', TRUE),
('OFFICE OF MANAGEMENT', 'government_excluded', TRUE),
('OFFICE SUPPLY REIMBURSEMENT', 'government_excluded', TRUE),
('OG&E', 'government_excluded', TRUE),
('OIL', 'government_excluded', TRUE),
('OLD MUTUAL', 'government_excluded', TRUE),
('ONCOR', 'government_excluded', TRUE),
('OPERATIONS', 'government_excluded', TRUE),
('OPTIMUM', 'government_excluded', TRUE),
('PACIFIC GAS & ELECTRIC', 'government_excluded', TRUE),
('PALO ALTO UTILITIES', 'government_excluded', TRUE),
('PARKER HANNIFIN CREDIT', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;