INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('REGIONAL BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('REGULATORY', 'System', 'Government/Financial exclusion keyword', TRUE),
('reimbursement', 'System', 'Government/Financial exclusion keyword', TRUE),
('RENTAL HOUSING', 'System', 'Government/Financial exclusion keyword', TRUE),
('RENTAL PAYMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('REPUBLIC SERVICES', 'System', 'Government/Financial exclusion keyword', TRUE),
('RESEARCH GRANT', 'System', 'Government/Financial exclusion keyword', TRUE),
('retirement', 'System', 'Government/Financial exclusion keyword', TRUE),
('REVENUE', 'System', 'Government/Financial exclusion keyword', TRUE),
('REVOLVING FUND', 'System', 'Government/Financial exclusion keyword', TRUE),
('RISK MANAGEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('ROAD COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('ROCKY MOUNTAIN POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('ROYAL BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('RSA', 'System', 'Government/Financial exclusion keyword', TRUE),
('SALT RIVER PROJECT', 'System', 'Government/Financial exclusion keyword', TRUE),
('SAVINGS', 'System', 'Government/Financial exclusion keyword', TRUE),
('SAVINGS & LOAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('SCHWAB', 'System', 'Government/Financial exclusion keyword', TRUE),
('SEC', 'System', 'Government/Financial exclusion keyword', TRUE),
('secretary of state', 'System', 'Government/Financial exclusion keyword', TRUE),
('secretary of treasury', 'System', 'Government/Financial exclusion keyword', TRUE),
('SECURITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('SECURITIES COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('SECURITY LIFE', 'System', 'Government/Financial exclusion keyword', TRUE),
('SEDGWICK', 'System', 'Government/Financial exclusion keyword', TRUE),
('SETTLEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('SEWER AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('SHERIFF', 'System', 'Government/Financial exclusion keyword', TRUE),
('SIGNAL MUTUAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('SIXTH DISTRICT', 'System', 'Government/Financial exclusion keyword', TRUE),
('SOCIAL SECURITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('SOLAR', 'System', 'Government/Financial exclusion keyword', TRUE),
('SOUTH CAROLINA ELECTRIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('SOUTHERN CALIFORNIA EDISON', 'System', 'Government/Financial exclusion keyword', TRUE),
('SOUTHERN COMPANY', 'System', 'Government/Financial exclusion keyword', TRUE),
('SOUTHWEST GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('SPACE AGENCY', 'System', 'Government/Financial exclusion keyword', TRUE),
('SPECTRUM', 'System', 'Government/Financial exclusion keyword', TRUE),
('SPRINT', 'System', 'Government/Financial exclusion keyword', TRUE),
('STANDARDS AGENCY', 'System', 'Government/Financial exclusion keyword', TRUE),
('STATE', 'System', 'Government/Financial exclusion keyword', TRUE),
('STATE BAR', 'System', 'Government/Financial exclusion keyword', TRUE),
('STATE FARM', 'System', 'Government/Financial exclusion keyword', TRUE),
('STATE OF', 'System', 'Government/Financial exclusion keyword', TRUE),
('STATE TAX', 'System', 'Government/Financial exclusion keyword', TRUE),
('STATE TREASURER', 'System', 'Government/Financial exclusion keyword', TRUE),
('STELLANTIS', 'System', 'Government/Financial exclusion keyword', TRUE),
('STREET OPENING PERMIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('SUBSIDY', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;