INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('REGIONAL BANK', 'government_excluded', TRUE),
('REGULATORY', 'government_excluded', TRUE),
('reimbursement', 'government_excluded', TRUE),
('RENTAL HOUSING', 'government_excluded', TRUE),
('RENTAL PAYMENT', 'government_excluded', TRUE),
('REPUBLIC SERVICES', 'government_excluded', TRUE),
('RESEARCH GRANT', 'government_excluded', TRUE),
('retirement', 'government_excluded', TRUE),
('REVENUE', 'government_excluded', TRUE),
('REVOLVING FUND', 'government_excluded', TRUE),
('RISK MANAGEMENT', 'government_excluded', TRUE),
('ROAD COMMISSION', 'government_excluded', TRUE),
('ROCKY MOUNTAIN POWER', 'government_excluded', TRUE),
('ROYAL BANK', 'government_excluded', TRUE),
('RSA', 'government_excluded', TRUE),
('SALT RIVER PROJECT', 'government_excluded', TRUE),
('SAVINGS', 'government_excluded', TRUE),
('SAVINGS & LOAN', 'government_excluded', TRUE),
('SCHWAB', 'government_excluded', TRUE),
('SEC', 'government_excluded', TRUE),
('secretary of state', 'government_excluded', TRUE),
('secretary of treasury', 'government_excluded', TRUE),
('SECURITIES', 'government_excluded', TRUE),
('SECURITIES COMMISSION', 'government_excluded', TRUE),
('SECURITY LIFE', 'government_excluded', TRUE),
('SEDGWICK', 'government_excluded', TRUE),
('SETTLEMENT', 'government_excluded', TRUE),
('SEWER AUTHORITY', 'government_excluded', TRUE),
('SHERIFF', 'government_excluded', TRUE),
('SIGNAL MUTUAL', 'government_excluded', TRUE),
('SIXTH DISTRICT', 'government_excluded', TRUE),
('SOCIAL SECURITY', 'government_excluded', TRUE),
('SOLAR', 'government_excluded', TRUE),
('SOUTH CAROLINA ELECTRIC', 'government_excluded', TRUE),
('SOUTHERN CALIFORNIA EDISON', 'government_excluded', TRUE),
('SOUTHERN COMPANY', 'government_excluded', TRUE),
('SOUTHWEST GAS', 'government_excluded', TRUE),
('SPACE AGENCY', 'government_excluded', TRUE),
('SPECTRUM', 'government_excluded', TRUE),
('SPRINT', 'government_excluded', TRUE),
('STANDARDS AGENCY', 'government_excluded', TRUE),
('STATE', 'government_excluded', TRUE),
('STATE BAR', 'government_excluded', TRUE),
('STATE FARM', 'government_excluded', TRUE),
('STATE OF', 'government_excluded', TRUE),
('STATE TAX', 'government_excluded', TRUE),
('STATE TREASURER', 'government_excluded', TRUE),
('STELLANTIS', 'government_excluded', TRUE),
('STREET OPENING PERMIT', 'government_excluded', TRUE),
('SUBSIDY', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;