INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('citi bank', 'System', 'Government/Financial exclusion keyword', TRUE),
('CITIBANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('CITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('CITY LIGHT', 'System', 'Government/Financial exclusion keyword', TRUE),
('CITY OF', 'System', 'Government/Financial exclusion keyword', TRUE),
('city treasurer', 'System', 'Government/Financial exclusion keyword', TRUE),
('CITY UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('CIVIC CENTER', 'System', 'Government/Financial exclusion keyword', TRUE),
('CLARKE ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('CLOUD COUNTY', 'System', 'Government/Financial exclusion keyword', TRUE),
('COBANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('COCA?COLA CREDIT UNION', 'System', 'Government/Financial exclusion keyword', TRUE),
('COLLEGE', 'System', 'Government/Financial exclusion keyword', TRUE),
('colonial life', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMCAST', 'System', 'Government/Financial exclusion keyword', TRUE),
('commercial card', 'System', 'Government/Financial exclusion keyword', TRUE),
('commerence bank', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMMITTEE', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMMONWEALTH', 'System', 'Government/Financial exclusion keyword', TRUE),
('commonwealth of', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMMUNITY BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMMUNITY COLLEGE', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMPENSATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('COMPTROLLER', 'System', 'Government/Financial exclusion keyword', TRUE),
('CON EDISON', 'System', 'Government/Financial exclusion keyword', TRUE),
('CONSERVANCY', 'System', 'Government/Financial exclusion keyword', TRUE),
('CONSOLIDATED', 'System', 'Government/Financial exclusion keyword', TRUE),
('CONSORTIUM', 'System', 'Government/Financial exclusion keyword', TRUE),
('Constellation', 'System', 'Government/Financial exclusion keyword', TRUE),
('CONSUMERS ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('CONTROLLER', 'System', 'Government/Financial exclusion keyword', TRUE),
('COOPERATIVE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CORPORATE TRUST', 'System', 'Government/Financial exclusion keyword', TRUE),
('corporate trust clearing', 'System', 'Government/Financial exclusion keyword', TRUE),
('CORPS OF ENGINEERS', 'System', 'Government/Financial exclusion keyword', TRUE),
('CORRECTIONAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('CORRECTIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('COUNTY', 'System', 'Government/Financial exclusion keyword', TRUE),
('county assessor', 'System', 'Government/Financial exclusion keyword', TRUE),
('county of', 'System', 'Government/Financial exclusion keyword', TRUE),
('county tax collector', 'System', 'Government/Financial exclusion keyword', TRUE),
('county treasurer', 'System', 'Government/Financial exclusion keyword', TRUE),
('COURT', 'System', 'Government/Financial exclusion keyword', TRUE),
('cox', 'System', 'Government/Financial exclusion keyword', TRUE),
('CREDIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('CREDIT ACCEPTANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CREDIT CARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('CREDIT CORP', 'System', 'Government/Financial exclusion keyword', TRUE),
('CREDIT ONE', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;