INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('ACCOUNTING OFFICE', 'government_excluded', TRUE),
('ACCOUNTS PAYABLE', 'government_excluded', TRUE),
('ADJUDICATION', 'government_excluded', TRUE),
('ADMINISTRATION', 'government_excluded', TRUE),
('ADP', 'government_excluded', TRUE),
('ADVANTA', 'government_excluded', TRUE),
('AEP', 'government_excluded', TRUE),
('AETNA', 'government_excluded', TRUE),
('aflac', 'government_excluded', TRUE),
('AGENCY', 'government_excluded', TRUE),
('AGRICULTURAL', 'government_excluded', TRUE),
('AIG', 'government_excluded', TRUE),
('alabama power', 'government_excluded', TRUE),
('alagasco', 'government_excluded', TRUE),
('ALLY', 'government_excluded', TRUE),
('ALPHERA FINANCIAL', 'government_excluded', TRUE),
('ALTRIA', 'government_excluded', TRUE),
('AMERICAN ELECTRIC', 'government_excluded', TRUE),
('AMERICAN EXPRESS', 'government_excluded', TRUE),
('AMERICAN FAMILY', 'government_excluded', TRUE),
('AMERIPRISE', 'government_excluded', TRUE),
('ameris bank', 'government_excluded', TRUE),
('AMERISURE', 'government_excluded', TRUE),
('AMEX', 'government_excluded', TRUE),
('AMICA', 'government_excluded', TRUE),
('ANNUITY', 'government_excluded', TRUE),
('ANTHEM', 'government_excluded', TRUE),
('ARBITRATION', 'government_excluded', TRUE),
('archer energy', 'government_excluded', TRUE),
('ARCHIVES', 'government_excluded', TRUE),
('ARIZONA PUBLIC SERVICE', 'government_excluded', TRUE),
('ARMY', 'government_excluded', TRUE),
('ARVEST BANK', 'government_excluded', TRUE),
('ASSET MANAGEMENT', 'government_excluded', TRUE),
('ASSURANCE', 'government_excluded', TRUE),
('ASYLUM', 'government_excluded', TRUE),
('AT & T', 'government_excluded', TRUE),
('AT&T', 'government_excluded', TRUE),
('ATT', 'government_excluded', TRUE),
('AUDIT', 'government_excluded', TRUE),
('AURORA ENERGY', 'government_excluded', TRUE),
('AUSTIN ENERGY', 'government_excluded', TRUE),
('AUTHORITY', 'government_excluded', TRUE),
('AVISTA', 'government_excluded', TRUE),
('AXA', 'government_excluded', TRUE),
('BANC', 'government_excluded', TRUE),
('BANC CORP', 'government_excluded', TRUE),
('BANCORP', 'government_excluded', TRUE),
('BANK', 'government_excluded', TRUE),
('Bank of', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;