INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('UNITED STATES', 'System', 'Government/Financial exclusion keyword', TRUE),
('UNIVERSITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('US BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('us dept of education', 'System', 'Government/Financial exclusion keyword', TRUE),
('us foods', 'System', 'Government/Financial exclusion keyword', TRUE),
('us postal service', 'System', 'Government/Financial exclusion keyword', TRUE),
('USAA', 'System', 'Government/Financial exclusion keyword', TRUE),
('USAA FEDERAL SAVINGS', 'System', 'Government/Financial exclusion keyword', TRUE),
('USDA', 'System', 'Government/Financial exclusion keyword', TRUE),
('usi insurance', 'System', 'Government/Financial exclusion keyword', TRUE),
('UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('UTILITY BOARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('VA', 'System', 'Government/Financial exclusion keyword', TRUE),
('VANGUARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('VERIZON', 'System', 'Government/Financial exclusion keyword', TRUE),
('VISA', 'System', 'Government/Financial exclusion keyword', TRUE),
('VISTRA', 'System', 'Government/Financial exclusion keyword', TRUE),
('WAGE', 'System', 'Government/Financial exclusion keyword', TRUE),
('WAGES', 'System', 'Government/Financial exclusion keyword', TRUE),
('WALNUT ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('WASTE MANAGEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('WATER', 'System', 'Government/Financial exclusion keyword', TRUE),
('WATER AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('WATER DISTRICT', 'System', 'Government/Financial exclusion keyword', TRUE),
('WATER FUND', 'System', 'Government/Financial exclusion keyword', TRUE),
('WEC ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('WELFARE', 'System', 'Government/Financial exclusion keyword', TRUE),
('WELLS FARGO', 'System', 'Government/Financial exclusion keyword', TRUE),
('WESTAR ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('WESTERN ALLIANCE BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('WEX', 'System', 'Government/Financial exclusion keyword', TRUE),
('WIRE', 'System', 'Government/Financial exclusion keyword', TRUE),
('WIRE TRANSFER', 'System', 'Government/Financial exclusion keyword', TRUE),
('WISCONSIN ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('WM SERVICES', 'System', 'Government/Financial exclusion keyword', TRUE),
('WORKERS COMPENSATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('WORKFORCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('WYNDHAM PROFITS', 'System', 'Government/Financial exclusion keyword', TRUE),
('XCEL ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('XFINITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('ZIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('ZIONS BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('ZURICH', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;