INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('SUPPLEMENTAL INSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('SUPREME COURT', 'System', 'Government/Financial exclusion keyword', TRUE),
('SYNNOVUS', 'System', 'Government/Financial exclusion keyword', TRUE),
('SYSCO', 'System', 'Government/Financial exclusion keyword', TRUE),
('TARIFF', 'System', 'Government/Financial exclusion keyword', TRUE),
('TAX', 'System', 'Government/Financial exclusion keyword', TRUE),
('tax collector', 'System', 'Government/Financial exclusion keyword', TRUE),
('TAX COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('TD', 'System', 'Government/Financial exclusion keyword', TRUE),
('TEACHERS RETIREMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('TELECOM', 'System', 'Government/Financial exclusion keyword', TRUE),
('TELECOMMUNICATIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('TENNESSEE VALLEY AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('THE CAPITAL GROUP', 'System', 'Government/Financial exclusion keyword', TRUE),
('THE COMMONWEALTH', 'System', 'Government/Financial exclusion keyword', TRUE),
('TIAA', 'System', 'Government/Financial exclusion keyword', TRUE),
('TJE COMPENSATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('tmobile', 'System', 'Government/Financial exclusion keyword', TRUE),
('t-mobile', 'System', 'Government/Financial exclusion keyword', TRUE),
('T?MOBILE', 'System', 'Government/Financial exclusion keyword', TRUE),
('Town of', 'System', 'Government/Financial exclusion keyword', TRUE),
('TOWNSHIP', 'System', 'Government/Financial exclusion keyword', TRUE),
('TOYOTA', 'System', 'Government/Financial exclusion keyword', TRUE),
('TOYOTA FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRADE COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRANSACTION SETTLEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRANSPORTATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRANSPORTATION AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('travelers', 'System', 'Government/Financial exclusion keyword', TRUE),
('TREASURER', 'System', 'Government/Financial exclusion keyword', TRUE),
('TREASURY', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRIBAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRINET', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRUIST', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRUST', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRUST COMPANY', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRUSTEE', 'System', 'Government/Financial exclusion keyword', TRUE),
('TRUSTEES', 'System', 'Government/Financial exclusion keyword', TRUE),
('TUTOR PERINI PAYROLL', 'System', 'Government/Financial exclusion keyword', TRUE),
('U S DEPARTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('U.S. DEPARTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('UAW TRUST', 'System', 'Government/Financial exclusion keyword', TRUE),
('UHC', 'System', 'Government/Financial exclusion keyword', TRUE),
('UKG', 'System', 'Government/Financial exclusion keyword', TRUE),
('UNEMPLOYMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('UNION', 'System', 'Government/Financial exclusion keyword', TRUE),
('UNION GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('UNITED HEALTH', 'System', 'Government/Financial exclusion keyword', TRUE),
('united healthcare', 'System', 'Government/Financial exclusion keyword', TRUE),
('united state treasury', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;