INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('BANK OF AMERICA', 'government_excluded', TRUE),
('BANKCORP', 'government_excluded', TRUE),
('BARCLAYS', 'government_excluded', TRUE),
('BAYLOR SCOTT & WHITE', 'government_excluded', TRUE),
('BENEFITS', 'government_excluded', TRUE),
('BEREAVEMENT', 'government_excluded', TRUE),
('BLUE CARE', 'government_excluded', TRUE),
('BLUE CROSS', 'government_excluded', TRUE),
('BLUE SHIELD', 'government_excluded', TRUE),
('BOARD', 'government_excluded', TRUE),
('BOARD OF EDUCATION', 'government_excluded', TRUE),
('board of trustees', 'government_excluded', TRUE),
('BOND', 'government_excluded', TRUE),
('BORDER', 'government_excluded', TRUE),
('BOROUGH', 'government_excluded', TRUE),
('BROKER', 'government_excluded', TRUE),
('BROKERAGE', 'government_excluded', TRUE),
('BUREAU', 'government_excluded', TRUE),
('BUSINESS TRUST', 'government_excluded', TRUE),
('CABELA?S CLUB VISA', 'government_excluded', TRUE),
('CALIFORNIA DEPARTMENT', 'government_excluded', TRUE),
('CALPERS', 'government_excluded', TRUE),
('CAPITAL', 'government_excluded', TRUE),
('CAPITAL GROUP', 'government_excluded', TRUE),
('CAPITAL ONE', 'government_excluded', TRUE),
('CAPITOL', 'government_excluded', TRUE),
('CAPTIVE FINANCE', 'government_excluded', TRUE),
('CARMAX AUTO FINANCE', 'government_excluded', TRUE),
('CAROLINA POWER', 'government_excluded', TRUE),
('CATERPILLAR FINANCIAL', 'government_excluded', TRUE),
('CBIZ PAYROLL', 'government_excluded', TRUE),
('CELTIC BANK', 'government_excluded', TRUE),
('census bureau', 'government_excluded', TRUE),
('CENTENE', 'government_excluded', TRUE),
('CENTRAL BANK', 'government_excluded', TRUE),
('CENTRAL HUDSON', 'government_excluded', TRUE),
('CENTURYLINK', 'government_excluded', TRUE),
('CERIDIAN', 'government_excluded', TRUE),
('CERRO GORDO COUNTY', 'government_excluded', TRUE),
('chamber of commerce', 'government_excluded', TRUE),
('CHARLES SCHWAB', 'government_excluded', TRUE),
('CHARLOTTE WATER', 'government_excluded', TRUE),
('CHARTER COMMUNICATIONS', 'government_excluded', TRUE),
('CHASE', 'government_excluded', TRUE),
('CHEVRON CREDIT', 'government_excluded', TRUE),
('child support', 'government_excluded', TRUE),
('CIGNA', 'government_excluded', TRUE),
('CINCINNATI BELL', 'government_excluded', TRUE),
('CIRCUIT COURT', 'government_excluded', TRUE),
('CITI', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;