INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('internal revenue service', 'System', 'Government/Financial exclusion keyword', TRUE),
('INTERNAL TRANSFER', 'System', 'Government/Financial exclusion keyword', TRUE),
('INTERNATIONAL MONETARY', 'System', 'Government/Financial exclusion keyword', TRUE),
('INVESTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('INVESTMENT BOARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('INVESTORS', 'System', 'Government/Financial exclusion keyword', TRUE),
('IRS', 'System', 'Government/Financial exclusion keyword', TRUE),
('ISO', 'System', 'Government/Financial exclusion keyword', TRUE),
('JP', 'System', 'Government/Financial exclusion keyword', TRUE),
('JP MORGAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('JPMORGAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('JUDICIARY', 'System', 'Government/Financial exclusion keyword', TRUE),
('KAISER', 'System', 'Government/Financial exclusion keyword', TRUE),
('KANSAS GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('KIA', 'System', 'Government/Financial exclusion keyword', TRUE),
('LABOR DEPARTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('LAND MANAGEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('LASALLE BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('LEASE', 'System', 'Government/Financial exclusion keyword', TRUE),
('LEASE FINANCING', 'System', 'Government/Financial exclusion keyword', TRUE),
('LEGISLATURE', 'System', 'Government/Financial exclusion keyword', TRUE),
('LENDING', 'System', 'Government/Financial exclusion keyword', TRUE),
('LENDING CLUB', 'System', 'Government/Financial exclusion keyword', TRUE),
('LIBERTY MUTUAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('LINE OF CREDIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('LOAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('LOAN PAYMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('LOAN SERVICING', 'System', 'Government/Financial exclusion keyword', TRUE),
('LOCKHEED MARTIN FCU', 'System', 'Government/Financial exclusion keyword', TRUE),
('LOTTERY COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('LPL FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('LUMEN TECHNOLOGIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('M&T', 'System', 'Government/Financial exclusion keyword', TRUE),
('MADISON GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('MAGELLAN HEALTH', 'System', 'Government/Financial exclusion keyword', TRUE),
('MAINE POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('MANUFACTURERS AND TRADERS', 'System', 'Government/Financial exclusion keyword', TRUE),
('MAPFRE', 'System', 'Government/Financial exclusion keyword', TRUE),
('MARGIN', 'System', 'Government/Financial exclusion keyword', TRUE),
('MARITIME', 'System', 'Government/Financial exclusion keyword', TRUE),
('MARSH', 'System', 'Government/Financial exclusion keyword', TRUE),
('MARSH & MCLENNAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('MAZDA', 'System', 'Government/Financial exclusion keyword', TRUE),
('MB FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('MCNA', 'System', 'Government/Financial exclusion keyword', TRUE),
('MDC UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('MEDICAID', 'System', 'Government/Financial exclusion keyword', TRUE),
('MEDICARE', 'System', 'Government/Financial exclusion keyword', TRUE),
('MEDICARE REIMBURSEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('MEDTRONIC FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;