INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('PAYCHEX', 'System', 'Government/Financial exclusion keyword', TRUE),
('PAYCOM', 'System', 'Government/Financial exclusion keyword', TRUE),
('PAYLOCITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PAYMENTUS', 'System', 'Government/Financial exclusion keyword', TRUE),
('PAYROLL', 'System', 'Government/Financial exclusion keyword', TRUE),
('PAYROLL SERVICE', 'System', 'Government/Financial exclusion keyword', TRUE),
('PENN Y M N C', 'System', 'Government/Financial exclusion keyword', TRUE),
('PENNYMAC', 'System', 'Government/Financial exclusion keyword', TRUE),
('PENSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('PENSION FUND', 'System', 'Government/Financial exclusion keyword', TRUE),
('PEOPLES GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('PERSHING', 'System', 'Government/Financial exclusion keyword', TRUE),
('petty cash', 'System', 'Government/Financial exclusion keyword', TRUE),
('PG&E', 'System', 'Government/Financial exclusion keyword', TRUE),
('PHARMACY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PHONE COMPANY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PHYSICIANS MUTUAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('PILGRIM', 'System', 'Government/Financial exclusion keyword', TRUE),
('PIMCO', 'System', 'Government/Financial exclusion keyword', TRUE),
('PNC', 'System', 'Government/Financial exclusion keyword', TRUE),
('PORT AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PORT POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('POSTAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('POWER AUTHORITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PPL ELECTRIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('PRA GROUP', 'System', 'Government/Financial exclusion keyword', TRUE),
('PRINCIPAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('PROBATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('PROCURATOR', 'System', 'Government/Financial exclusion keyword', TRUE),
('PROCUREMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('PROGRESSIVE', 'System', 'Government/Financial exclusion keyword', TRUE),
('PROGRESSIVE ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PRUDENTIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC BROADCASTING', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC HEALTH', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC SAFETY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC SERVICE COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC SERVICE COMPANY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC UTILITIES COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC UTILITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('PUBLIC WORKS', 'System', 'Government/Financial exclusion keyword', TRUE),
('PURCHASE CARD PAYMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('RAILROAD', 'System', 'Government/Financial exclusion keyword', TRUE),
('REAL ESTATE', 'System', 'Government/Financial exclusion keyword', TRUE),
('REAL ESTATE AND RENTAL AND LEASING', 'System', 'Government/Financial exclusion keyword', TRUE),
('RECLAMATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('REDEVELOPMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('REGENTS', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;