INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('PAYCHEX', 'government_excluded', TRUE),
('PAYCOM', 'government_excluded', TRUE),
('PAYLOCITY', 'government_excluded', TRUE),
('PAYMENTUS', 'government_excluded', TRUE),
('PAYROLL', 'government_excluded', TRUE),
('PAYROLL SERVICE', 'government_excluded', TRUE),
('PENN Y M N C', 'government_excluded', TRUE),
('PENNYMAC', 'government_excluded', TRUE),
('PENSION', 'government_excluded', TRUE),
('PENSION FUND', 'government_excluded', TRUE),
('PEOPLES GAS', 'government_excluded', TRUE),
('PERSHING', 'government_excluded', TRUE),
('petty cash', 'government_excluded', TRUE),
('PG&E', 'government_excluded', TRUE),
('PHARMACY', 'government_excluded', TRUE),
('PHONE COMPANY', 'government_excluded', TRUE),
('PHYSICIANS MUTUAL', 'government_excluded', TRUE),
('PILGRIM', 'government_excluded', TRUE),
('PIMCO', 'government_excluded', TRUE),
('PNC', 'government_excluded', TRUE),
('PORT AUTHORITY', 'government_excluded', TRUE),
('PORT POWER', 'government_excluded', TRUE),
('POSTAL', 'government_excluded', TRUE),
('POWER', 'government_excluded', TRUE),
('POWER AUTHORITY', 'government_excluded', TRUE),
('PPL ELECTRIC', 'government_excluded', TRUE),
('PRA GROUP', 'government_excluded', TRUE),
('PRINCIPAL', 'government_excluded', TRUE),
('PROBATION', 'government_excluded', TRUE),
('PROCURATOR', 'government_excluded', TRUE),
('PROCUREMENT', 'government_excluded', TRUE),
('PROGRESSIVE', 'government_excluded', TRUE),
('PROGRESSIVE ENERGY', 'government_excluded', TRUE),
('PRUDENTIAL', 'government_excluded', TRUE),
('PUBLIC BROADCASTING', 'government_excluded', TRUE),
('PUBLIC HEALTH', 'government_excluded', TRUE),
('PUBLIC SAFETY', 'government_excluded', TRUE),
('PUBLIC SERVICE COMMISSION', 'government_excluded', TRUE),
('PUBLIC SERVICE COMPANY', 'government_excluded', TRUE),
('PUBLIC UTILITIES', 'government_excluded', TRUE),
('PUBLIC UTILITIES COMMISSION', 'government_excluded', TRUE),
('PUBLIC UTILITY', 'government_excluded', TRUE),
('PUBLIC WORKS', 'government_excluded', TRUE),
('PURCHASE CARD PAYMENT', 'government_excluded', TRUE),
('RAILROAD', 'government_excluded', TRUE),
('REAL ESTATE', 'government_excluded', TRUE),
('REAL ESTATE AND RENTAL AND LEASING', 'government_excluded', TRUE),
('RECLAMATION', 'government_excluded', TRUE),
('REDEVELOPMENT', 'government_excluded', TRUE),
('REGENTS', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;