INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('ERICSSON CREDIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('ESA PAYROLL', 'System', 'Government/Financial exclusion keyword', TRUE),
('ESCROW', 'System', 'Government/Financial exclusion keyword', TRUE),
('EVERSOURCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('EXCELLUS', 'System', 'Government/Financial exclusion keyword', TRUE),
('EXCISE', 'System', 'Government/Financial exclusion keyword', TRUE),
('EXPENSE REIMBURSEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('EXPRESS SCRIPTS', 'System', 'Government/Financial exclusion keyword', TRUE),
('F&B', 'System', 'Government/Financial exclusion keyword', TRUE),
('family trust', 'System', 'Government/Financial exclusion keyword', TRUE),
('FANNIE MAE', 'System', 'Government/Financial exclusion keyword', TRUE),
('FARM BUREAU', 'System', 'Government/Financial exclusion keyword', TRUE),
('FARM CREDIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('farmers and merchants bank', 'System', 'Government/Financial exclusion keyword', TRUE),
('FARMERS INSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('FBI', 'System', 'Government/Financial exclusion keyword', TRUE),
('FDIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('FEDERAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('FEDERAL EXPRESS FREIGHT', 'System', 'Government/Financial exclusion keyword', TRUE),
('FEDERAL RESERVE', 'System', 'Government/Financial exclusion keyword', TRUE),
('FEDEX FREIGHT PAYMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('FEMA', 'System', 'Government/Financial exclusion keyword', TRUE),
('FIDELITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('FIDUCIARY', 'System', 'Government/Financial exclusion keyword', TRUE),
('FIFTH THIRD', 'System', 'Government/Financial exclusion keyword', TRUE),
('FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('FINANCE AND INSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('FINANCIAL ENFORCEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('FIRM', 'System', 'Government/Financial exclusion keyword', TRUE),
('first american title', 'System', 'Government/Financial exclusion keyword', TRUE),
('FISCAL SERVICE', 'System', 'Government/Financial exclusion keyword', TRUE),
('FISCAL SERVICES', 'System', 'Government/Financial exclusion keyword', TRUE),
('FLEET', 'System', 'Government/Financial exclusion keyword', TRUE),
('FLORIDA POWER & LIGHT', 'System', 'Government/Financial exclusion keyword', TRUE),
('FORESTRY', 'System', 'Government/Financial exclusion keyword', TRUE),
('FORTIS', 'System', 'Government/Financial exclusion keyword', TRUE),
('foundation', 'System', 'Government/Financial exclusion keyword', TRUE),
('FRANCHISE TAX', 'System', 'Government/Financial exclusion keyword', TRUE),
('FRONTIER COMMUNICATIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('FUND', 'System', 'Government/Financial exclusion keyword', TRUE),
('FUNDING', 'System', 'Government/Financial exclusion keyword', TRUE),
('FUNDS', 'System', 'Government/Financial exclusion keyword', TRUE),
('FUTURES', 'System', 'Government/Financial exclusion keyword', TRUE),
('G&K SERVICES', 'System', 'Government/Financial exclusion keyword', TRUE),
('GALLAGHER BENEFIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('GAMING COMMISSION', 'System', 'Government/Financial exclusion keyword', TRUE),
('GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('GAS CO', 'System', 'Government/Financial exclusion keyword', TRUE),
('GAS COMPANY', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;