INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('CREDIT UNION', 'government_excluded', TRUE),
('CREDITORS', 'government_excluded', TRUE),
('CROWN CASTLE', 'government_excluded', TRUE),
('CUSTODIAN', 'government_excluded', TRUE),
('CUSTOMS', 'government_excluded', TRUE),
('D&B', 'government_excluded', TRUE),
('DEACONESS', 'government_excluded', TRUE),
('DEBT', 'government_excluded', TRUE),
('DEBT COLLECTION', 'government_excluded', TRUE),
('DECATUR UTILITIES', 'government_excluded', TRUE),
('DEFENSE', 'government_excluded', TRUE),
('DEFERRED COMP', 'government_excluded', TRUE),
('DELAWARE POWER', 'government_excluded', TRUE),
('delta dental', 'government_excluded', TRUE),
('DEPARTMENT', 'government_excluded', TRUE),
('department of labor', 'government_excluded', TRUE),
('department of revenue', 'government_excluded', TRUE),
('department of taxation', 'government_excluded', TRUE),
('DEPOSITORY', 'government_excluded', TRUE),
('dept of revenue', 'government_excluded', TRUE),
('dept of taxation', 'government_excluded', TRUE),
('DES MOINES WATER', 'government_excluded', TRUE),
('disbursement', 'government_excluded', TRUE),
('DIVISION', 'government_excluded', TRUE),
('DOD', 'government_excluded', TRUE),
('DOMINION ENERGY', 'government_excluded', TRUE),
('DOT', 'government_excluded', TRUE),
('DUKE ENERGY', 'government_excluded', TRUE),
('EASTERN BANK', 'government_excluded', TRUE),
('EATON VANCE', 'government_excluded', TRUE),
('ELECTRIC', 'government_excluded', TRUE),
('ELECTRIC CO', 'government_excluded', TRUE),
('ELECTRIC CO?OP', 'government_excluded', TRUE),
('ELECTRIC COOPERATIVE', 'government_excluded', TRUE),
('ELECTRICAL', 'government_excluded', TRUE),
('ELEMENT FLEET', 'government_excluded', TRUE),
('ELIGIBILITY OFFICE', 'government_excluded', TRUE),
('ELIZABETHTOWN GAS', 'government_excluded', TRUE),
('EMERA', 'government_excluded', TRUE),
('EMPLOYEE', 'government_excluded', TRUE),
('EMPLOYEE BENEFIT', 'government_excluded', TRUE),
('EMPLOYEE BENEFIT BOARD', 'government_excluded', TRUE),
('EMPLOYEE EXPENSE', 'government_excluded', TRUE),
('EMPLOYEES RETIREMENT', 'government_excluded', TRUE),
('ENERGY', 'government_excluded', TRUE),
('ENFORCEMENT', 'government_excluded', TRUE),
('ENTERGY', 'government_excluded', TRUE),
('ENVIRONMENTAL', 'government_excluded', TRUE),
('EQUAL OPPORTUNITY', 'government_excluded', TRUE),
('EQUITY TRUST', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;