INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('GE CAPITAL', 'government_excluded', TRUE),
('GE HEALTHCARE FINANCE', 'government_excluded', TRUE),
('GEICO', 'government_excluded', TRUE),
('GENERAL SERVICES', 'government_excluded', TRUE),
('GEORGIA POWER', 'government_excluded', TRUE),
('GM', 'government_excluded', TRUE),
('GM FINANCIAL', 'government_excluded', TRUE),
('GOVERNING BOARD', 'government_excluded', TRUE),
('GOVERNMENT', 'government_excluded', TRUE),
('GOVERNOR', 'government_excluded', TRUE),
('GRACE PERIOD TRUST', 'government_excluded', TRUE),
('GRANT', 'government_excluded', TRUE),
('GREAT PLAINS ENERGY', 'government_excluded', TRUE),
('GREEN DOT BANK', 'government_excluded', TRUE),
('GUARDIAN LIFE', 'government_excluded', TRUE),
('GUSTO', 'government_excluded', TRUE),
('HARBOR', 'government_excluded', TRUE),
('HARTFORD', 'government_excluded', TRUE),
('HEALTH AND HUMAN SERVICES', 'government_excluded', TRUE),
('HEALTH BENEFIT FUND', 'government_excluded', TRUE),
('HEALTH DEPARTMENT', 'government_excluded', TRUE),
('HEALTH INSURANCE', 'government_excluded', TRUE),
('HEALTHSPRING', 'government_excluded', TRUE),
('HIGHMARK', 'government_excluded', TRUE),
('HMRC', 'government_excluded', TRUE),
('HOLDINGS', 'government_excluded', TRUE),
('HOME EQUITY', 'government_excluded', TRUE),
('HOMELAND SECURITY', 'government_excluded', TRUE),
('HONDA', 'government_excluded', TRUE),
('HONDA FINANCE', 'government_excluded', TRUE),
('HOUSING AUTHORITY', 'government_excluded', TRUE),
('HOUSING FINANCE', 'government_excluded', TRUE),
('HUD', 'government_excluded', TRUE),
('HUMANA', 'government_excluded', TRUE),
('HUNTINGTON BANCSHARES', 'government_excluded', TRUE),
('HYDRO', 'government_excluded', TRUE),
('HYUNDAI', 'government_excluded', TRUE),
('IMMIGRATION', 'government_excluded', TRUE),
('IMPORT EXPORT', 'government_excluded', TRUE),
('INDIVIDUAL ACH PAYMENT', 'government_excluded', TRUE),
('INDUSTRIAL DEVELOPMENT', 'government_excluded', TRUE),
('INDUSTRIAL RELATIONS', 'government_excluded', TRUE),
('INSPECTION', 'government_excluded', TRUE),
('INSPECTORATE', 'government_excluded', TRUE),
('INSURANCE', 'government_excluded', TRUE),
('INSURANCE COMMISSION', 'government_excluded', TRUE),
('INSURER', 'government_excluded', TRUE),
('INTELLECTUAL PROPERTY', 'government_excluded', TRUE),
('INTERCOMPANY', 'government_excluded', TRUE),
('INTERNAL REVENUE', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;