INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('SUPPLEMENTAL INSURANCE', 'government_excluded', TRUE),
('SUPREME COURT', 'government_excluded', TRUE),
('SYNNOVUS', 'government_excluded', TRUE),
('SYSCO', 'government_excluded', TRUE),
('TARIFF', 'government_excluded', TRUE),
('TAX', 'government_excluded', TRUE),
('tax collector', 'government_excluded', TRUE),
('TAX COMMISSION', 'government_excluded', TRUE),
('TD', 'government_excluded', TRUE),
('TEACHERS RETIREMENT', 'government_excluded', TRUE),
('TELECOM', 'government_excluded', TRUE),
('TELECOMMUNICATIONS', 'government_excluded', TRUE),
('TENNESSEE VALLEY AUTHORITY', 'government_excluded', TRUE),
('THE CAPITAL GROUP', 'government_excluded', TRUE),
('THE COMMONWEALTH', 'government_excluded', TRUE),
('TIAA', 'government_excluded', TRUE),
('TJE COMPENSATION', 'government_excluded', TRUE),
('tmobile', 'government_excluded', TRUE),
('t-mobile', 'government_excluded', TRUE),
('T?MOBILE', 'government_excluded', TRUE),
('Town of', 'government_excluded', TRUE),
('TOWNSHIP', 'government_excluded', TRUE),
('TOYOTA', 'government_excluded', TRUE),
('TOYOTA FINANCIAL', 'government_excluded', TRUE),
('TRADE COMMISSION', 'government_excluded', TRUE),
('TRANSACTION SETTLEMENT', 'government_excluded', TRUE),
('TRANSPORTATION', 'government_excluded', TRUE),
('TRANSPORTATION AUTHORITY', 'government_excluded', TRUE),
('travelers', 'government_excluded', TRUE),
('TREASURER', 'government_excluded', TRUE),
('TREASURY', 'government_excluded', TRUE),
('TRIBAL', 'government_excluded', TRUE),
('TRINET', 'government_excluded', TRUE),
('TRUIST', 'government_excluded', TRUE),
('TRUST', 'government_excluded', TRUE),
('TRUST COMPANY', 'government_excluded', TRUE),
('TRUSTEE', 'government_excluded', TRUE),
('TRUSTEES', 'government_excluded', TRUE),
('TUTOR PERINI PAYROLL', 'government_excluded', TRUE),
('U S DEPARTMENT', 'government_excluded', TRUE),
('U.S. DEPARTMENT', 'government_excluded', TRUE),
('UAW TRUST', 'government_excluded', TRUE),
('UHC', 'government_excluded', TRUE),
('UKG', 'government_excluded', TRUE),
('UNEMPLOYMENT', 'government_excluded', TRUE),
('UNION', 'government_excluded', TRUE),
('UNION GAS', 'government_excluded', TRUE),
('UNITED HEALTH', 'government_excluded', TRUE),
('united healthcare', 'government_excluded', TRUE),
('united state treasury', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;