INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('UNITED STATES', 'government_excluded', TRUE),
('UNIVERSITY', 'government_excluded', TRUE),
('US BANK', 'government_excluded', TRUE),
('us dept of education', 'government_excluded', TRUE),
('us foods', 'government_excluded', TRUE),
('us postal service', 'government_excluded', TRUE),
('USAA', 'government_excluded', TRUE),
('USAA FEDERAL SAVINGS', 'government_excluded', TRUE),
('USDA', 'government_excluded', TRUE),
('usi insurance', 'government_excluded', TRUE),
('UTILITIES', 'government_excluded', TRUE),
('UTILITY BOARD', 'government_excluded', TRUE),
('VA', 'government_excluded', TRUE),
('VANGUARD', 'government_excluded', TRUE),
('VERIZON', 'government_excluded', TRUE),
('VISA', 'government_excluded', TRUE),
('VISTRA', 'government_excluded', TRUE),
('WAGE', 'government_excluded', TRUE),
('WAGES', 'government_excluded', TRUE),
('WALNUT ENERGY', 'government_excluded', TRUE),
('WASTE MANAGEMENT', 'government_excluded', TRUE),
('WATER', 'government_excluded', TRUE),
('WATER AUTHORITY', 'government_excluded', TRUE),
('WATER DISTRICT', 'government_excluded', TRUE),
('WATER FUND', 'government_excluded', TRUE),
('WEC ENERGY', 'government_excluded', TRUE),
('WELFARE', 'government_excluded', TRUE),
('WELLS FARGO', 'government_excluded', TRUE),
('WESTAR ENERGY', 'government_excluded', TRUE),
('WESTERN ALLIANCE BANK', 'government_excluded', TRUE),
('WEX', 'government_excluded', TRUE),
('WIRE', 'government_excluded', TRUE),
('WIRE TRANSFER', 'government_excluded', TRUE),
('WISCONSIN ENERGY', 'government_excluded', TRUE),
('WM SERVICES', 'government_excluded', TRUE),
('WORKERS COMPENSATION', 'government_excluded', TRUE),
('WORKFORCE', 'government_excluded', TRUE),
('WYNDHAM PROFITS', 'government_excluded', TRUE),
('XCEL ENERGY', 'government_excluded', TRUE),
('XFINITY', 'government_excluded', TRUE),
('ZIONS', 'government_excluded', TRUE),
('ZIONS BANK', 'government_excluded', TRUE),
('ZURICH', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;