INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('citi bank', 'government_excluded', TRUE),
('CITIBANK', 'government_excluded', TRUE),
('CITY', 'government_excluded', TRUE),
('CITY LIGHT', 'government_excluded', TRUE),
('CITY OF', 'government_excluded', TRUE),
('city treasurer', 'government_excluded', TRUE),
('CITY UTILITIES', 'government_excluded', TRUE),
('CIVIC CENTER', 'government_excluded', TRUE),
('CLARKE ENERGY', 'government_excluded', TRUE),
('CLOUD COUNTY', 'government_excluded', TRUE),
('COBANK', 'government_excluded', TRUE),
('COCA?COLA CREDIT UNION', 'government_excluded', TRUE),
('COLLEGE', 'government_excluded', TRUE),
('colonial life', 'government_excluded', TRUE),
('COMCAST', 'government_excluded', TRUE),
('commercial card', 'government_excluded', TRUE),
('commerence bank', 'government_excluded', TRUE),
('COMMISSION', 'government_excluded', TRUE),
('COMMITTEE', 'government_excluded', TRUE),
('COMMONWEALTH', 'government_excluded', TRUE),
('commonwealth of', 'government_excluded', TRUE),
('COMMUNITY BANK', 'government_excluded', TRUE),
('COMMUNITY COLLEGE', 'government_excluded', TRUE),
('COMPENSATION', 'government_excluded', TRUE),
('COMPTROLLER', 'government_excluded', TRUE),
('CON EDISON', 'government_excluded', TRUE),
('CONSERVANCY', 'government_excluded', TRUE),
('CONSOLIDATED', 'government_excluded', TRUE),
('CONSORTIUM', 'government_excluded', TRUE),
('Constellation', 'government_excluded', TRUE),
('CONSUMERS ENERGY', 'government_excluded', TRUE),
('CONTROLLER', 'government_excluded', TRUE),
('COOPERATIVE', 'government_excluded', TRUE),
('CORPORATE TRUST', 'government_excluded', TRUE),
('corporate trust clearing', 'government_excluded', TRUE),
('CORPS OF ENGINEERS', 'government_excluded', TRUE),
('CORRECTIONAL', 'government_excluded', TRUE),
('CORRECTIONS', 'government_excluded', TRUE),
('COUNTY', 'government_excluded', TRUE),
('county assessor', 'government_excluded', TRUE),
('county of', 'government_excluded', TRUE),
('county tax collector', 'government_excluded', TRUE),
('county treasurer', 'government_excluded', TRUE),
('COURT', 'government_excluded', TRUE),
('cox', 'government_excluded', TRUE),
('CREDIT', 'government_excluded', TRUE),
('CREDIT ACCEPTANCE', 'government_excluded', TRUE),
('CREDIT CARD', 'government_excluded', TRUE),
('CREDIT CORP', 'government_excluded', TRUE),
('CREDIT ONE', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;