INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('CREDIT UNION', 'System', 'Government/Financial exclusion keyword', TRUE),
('CREDITORS', 'System', 'Government/Financial exclusion keyword', TRUE),
('CROWN CASTLE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CUSTODIAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('CUSTOMS', 'System', 'Government/Financial exclusion keyword', TRUE),
('D&B', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEACONESS', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEBT', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEBT COLLECTION', 'System', 'Government/Financial exclusion keyword', TRUE),
('DECATUR UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEFENSE', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEFERRED COMP', 'System', 'Government/Financial exclusion keyword', TRUE),
('DELAWARE POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('delta dental', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEPARTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('department of labor', 'System', 'Government/Financial exclusion keyword', TRUE),
('department of revenue', 'System', 'Government/Financial exclusion keyword', TRUE),
('department of taxation', 'System', 'Government/Financial exclusion keyword', TRUE),
('DEPOSITORY', 'System', 'Government/Financial exclusion keyword', TRUE),
('dept of revenue', 'System', 'Government/Financial exclusion keyword', TRUE),
('dept of taxation', 'System', 'Government/Financial exclusion keyword', TRUE),
('DES MOINES WATER', 'System', 'Government/Financial exclusion keyword', TRUE),
('disbursement', 'System', 'Government/Financial exclusion keyword', TRUE),
('DIVISION', 'System', 'Government/Financial exclusion keyword', TRUE),
('DOD', 'System', 'Government/Financial exclusion keyword', TRUE),
('DOMINION ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('DOT', 'System', 'Government/Financial exclusion keyword', TRUE),
('DUKE ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('EASTERN BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('EATON VANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELECTRIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELECTRIC CO', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELECTRIC CO?OP', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELECTRIC COOPERATIVE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELECTRICAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELEMENT FLEET', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELIGIBILITY OFFICE', 'System', 'Government/Financial exclusion keyword', TRUE),
('ELIZABETHTOWN GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('EMERA', 'System', 'Government/Financial exclusion keyword', TRUE),
('EMPLOYEE', 'System', 'Government/Financial exclusion keyword', TRUE),
('EMPLOYEE BENEFIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('EMPLOYEE BENEFIT BOARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('EMPLOYEE EXPENSE', 'System', 'Government/Financial exclusion keyword', TRUE),
('EMPLOYEES RETIREMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('ENERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('ENFORCEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('ENTERGY', 'System', 'Government/Financial exclusion keyword', TRUE),
('ENVIRONMENTAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('EQUAL OPPORTUNITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('EQUITY TRUST', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;