INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('MELLON', 'System', 'Government/Financial exclusion keyword', TRUE),
('MEMORIAL HOSPITAL PAYROLL', 'System', 'Government/Financial exclusion keyword', TRUE),
('MERCEDES BENZ FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('merrill lynch', 'System', 'Government/Financial exclusion keyword', TRUE),
('MERS', 'System', 'Government/Financial exclusion keyword', TRUE),
('METLIFE', 'System', 'Government/Financial exclusion keyword', TRUE),
('METRO WATER', 'System', 'Government/Financial exclusion keyword', TRUE),
('MILITARY', 'System', 'Government/Financial exclusion keyword', TRUE),
('MILLIMAN BENEFITS', 'System', 'Government/Financial exclusion keyword', TRUE),
('MINING', 'System', 'Government/Financial exclusion keyword', TRUE),
('MINNESOTA POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('MIZUHO', 'System', 'Government/Financial exclusion keyword', TRUE),
('MORGAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('MORGAN STANLEY', 'System', 'Government/Financial exclusion keyword', TRUE),
('MORTGAGE', 'System', 'Government/Financial exclusion keyword', TRUE),
('MORTGAGE COMPANY', 'System', 'Government/Financial exclusion keyword', TRUE),
('MORTGAGE SERVICING', 'System', 'Government/Financial exclusion keyword', TRUE),
('MOSAIC PAYMENTS', 'System', 'Government/Financial exclusion keyword', TRUE),
('MTA', 'System', 'Government/Financial exclusion keyword', TRUE),
('MUNICIPAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('MUNICIPAL ELECTRIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('MUNICIPAL POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('MUNICIPALITY', 'System', 'Government/Financial exclusion keyword', TRUE),
('mututal of omaha', 'System', 'Government/Financial exclusion keyword', TRUE),
('NATIONAL BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('NATIONAL FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('NATIONAL GRID', 'System', 'Government/Financial exclusion keyword', TRUE),
('NATIONAL TREASURY', 'System', 'Government/Financial exclusion keyword', TRUE),
('NAVY', 'System', 'Government/Financial exclusion keyword', TRUE),
('NCR', 'System', 'Government/Financial exclusion keyword', TRUE),
('NEW JERSEY UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('NISSAN MOTOR ACCEPTANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('NORTHERN NATURAL GAS', 'System', 'Government/Financial exclusion keyword', TRUE),
('NORTHWESTERN MUTUAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('NSTAR', 'System', 'Government/Financial exclusion keyword', TRUE),
('NUCLEAR', 'System', 'Government/Financial exclusion keyword', TRUE),
('OCCUPATIONAL SAFETY', 'System', 'Government/Financial exclusion keyword', TRUE),
('OCEAN VIEW INSURANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('OFFICE OF', 'System', 'Government/Financial exclusion keyword', TRUE),
('OFFICE OF MANAGEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('OFFICE SUPPLY REIMBURSEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('OG&E', 'System', 'Government/Financial exclusion keyword', TRUE),
('OIL', 'System', 'Government/Financial exclusion keyword', TRUE),
('OLD MUTUAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('ONCOR', 'System', 'Government/Financial exclusion keyword', TRUE),
('OPERATIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('OPTIMUM', 'System', 'Government/Financial exclusion keyword', TRUE),
('PACIFIC GAS & ELECTRIC', 'System', 'Government/Financial exclusion keyword', TRUE),
('PALO ALTO UTILITIES', 'System', 'Government/Financial exclusion keyword', TRUE),
('PARKER HANNIFIN CREDIT', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;