INSERT INTO exclusion_keywords (keyword, added_by, notes, is_active) VALUES
('BANK OF AMERICA', 'System', 'Government/Financial exclusion keyword', TRUE),
('BANKCORP', 'System', 'Government/Financial exclusion keyword', TRUE),
('BARCLAYS', 'System', 'Government/Financial exclusion keyword', TRUE),
('BAYLOR SCOTT & WHITE', 'System', 'Government/Financial exclusion keyword', TRUE),
('BENEFITS', 'System', 'Government/Financial exclusion keyword', TRUE),
('BEREAVEMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('BLUE CARE', 'System', 'Government/Financial exclusion keyword', TRUE),
('BLUE CROSS', 'System', 'Government/Financial exclusion keyword', TRUE),
('BLUE SHIELD', 'System', 'Government/Financial exclusion keyword', TRUE),
('BOARD', 'System', 'Government/Financial exclusion keyword', TRUE),
('BOARD OF EDUCATION', 'System', 'Government/Financial exclusion keyword', TRUE),
('board of trustees', 'System', 'Government/Financial exclusion keyword', TRUE),
('BOND', 'System', 'Government/Financial exclusion keyword', TRUE),
('BORDER', 'System', 'Government/Financial exclusion keyword', TRUE),
('BOROUGH', 'System', 'Government/Financial exclusion keyword', TRUE),
('BROKER', 'System', 'Government/Financial exclusion keyword', TRUE),
('BROKERAGE', 'System', 'Government/Financial exclusion keyword', TRUE),
('BUREAU', 'System', 'Government/Financial exclusion keyword', TRUE),
('BUSINESS TRUST', 'System', 'Government/Financial exclusion keyword', TRUE),
('CABELA?S CLUB VISA', 'System', 'Government/Financial exclusion keyword', TRUE),
('CALIFORNIA DEPARTMENT', 'System', 'Government/Financial exclusion keyword', TRUE),
('CALPERS', 'System', 'Government/Financial exclusion keyword', TRUE),
('CAPITAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('CAPITAL GROUP', 'System', 'Government/Financial exclusion keyword', TRUE),
('CAPITAL ONE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CAPITOL', 'System', 'Government/Financial exclusion keyword', TRUE),
('CAPTIVE FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CARMAX AUTO FINANCE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CAROLINA POWER', 'System', 'Government/Financial exclusion keyword', TRUE),
('CATERPILLAR FINANCIAL', 'System', 'Government/Financial exclusion keyword', TRUE),
('CBIZ PAYROLL', 'System', 'Government/Financial exclusion keyword', TRUE),
('CELTIC BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('census bureau', 'System', 'Government/Financial exclusion keyword', TRUE),
('CENTENE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CENTRAL BANK', 'System', 'Government/Financial exclusion keyword', TRUE),
('CENTRAL HUDSON', 'System', 'Government/Financial exclusion keyword', TRUE),
('CENTURYLINK', 'System', 'Government/Financial exclusion keyword', TRUE),
('CERIDIAN', 'System', 'Government/Financial exclusion keyword', TRUE),
('CERRO GORDO COUNTY', 'System', 'Government/Financial exclusion keyword', TRUE),
('chamber of commerce', 'System', 'Government/Financial exclusion keyword', TRUE),
('CHARLES SCHWAB', 'System', 'Government/Financial exclusion keyword', TRUE),
('CHARLOTTE WATER', 'System', 'Government/Financial exclusion keyword', TRUE),
('CHARTER COMMUNICATIONS', 'System', 'Government/Financial exclusion keyword', TRUE),
('CHASE', 'System', 'Government/Financial exclusion keyword', TRUE),
('CHEVRON CREDIT', 'System', 'Government/Financial exclusion keyword', TRUE),
('child support', 'System', 'Government/Financial exclusion keyword', TRUE),
('CIGNA', 'System', 'Government/Financial exclusion keyword', TRUE),
('CINCINNATI BELL', 'System', 'Government/Financial exclusion keyword', TRUE),
('CIRCUIT COURT', 'System', 'Government/Financial exclusion keyword', TRUE),
('CITI', 'System', 'Government/Financial exclusion keyword', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;