INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('internal revenue service', 'government_excluded', TRUE),
('INTERNAL TRANSFER', 'government_excluded', TRUE),
('INTERNATIONAL MONETARY', 'government_excluded', TRUE),
('INVESTMENT', 'government_excluded', TRUE),
('INVESTMENT BOARD', 'government_excluded', TRUE),
('INVESTORS', 'government_excluded', TRUE),
('IRS', 'government_excluded', TRUE),
('ISO', 'government_excluded', TRUE),
('JP', 'government_excluded', TRUE),
('JP MORGAN', 'government_excluded', TRUE),
('JPMORGAN', 'government_excluded', TRUE),
('JUDICIARY', 'government_excluded', TRUE),
('KAISER', 'government_excluded', TRUE),
('KANSAS GAS', 'government_excluded', TRUE),
('KIA', 'government_excluded', TRUE),
('LABOR DEPARTMENT', 'government_excluded', TRUE),
('LAND MANAGEMENT', 'government_excluded', TRUE),
('LASALLE BANK', 'government_excluded', TRUE),
('LEASE', 'government_excluded', TRUE),
('LEASE FINANCING', 'government_excluded', TRUE),
('LEGISLATURE', 'government_excluded', TRUE),
('LENDING', 'government_excluded', TRUE),
('LENDING CLUB', 'government_excluded', TRUE),
('LIBERTY MUTUAL', 'government_excluded', TRUE),
('LINE OF CREDIT', 'government_excluded', TRUE),
('LOAN', 'government_excluded', TRUE),
('LOAN PAYMENT', 'government_excluded', TRUE),
('LOAN SERVICING', 'government_excluded', TRUE),
('LOCKHEED MARTIN FCU', 'government_excluded', TRUE),
('LOTTERY COMMISSION', 'government_excluded', TRUE),
('LPL FINANCIAL', 'government_excluded', TRUE),
('LUMEN TECHNOLOGIES', 'government_excluded', TRUE),
('M&T', 'government_excluded', TRUE),
('MADISON GAS', 'government_excluded', TRUE),
('MAGELLAN HEALTH', 'government_excluded', TRUE),
('MAINE POWER', 'government_excluded', TRUE),
('MANUFACTURERS AND TRADERS', 'government_excluded', TRUE),
('MAPFRE', 'government_excluded', TRUE),
('MARGIN', 'government_excluded', TRUE),
('MARITIME', 'government_excluded', TRUE),
('MARSH', 'government_excluded', TRUE),
('MARSH & MCLENNAN', 'government_excluded', TRUE),
('MAZDA', 'government_excluded', TRUE),
('MB FINANCIAL', 'government_excluded', TRUE),
('MCNA', 'government_excluded', TRUE),
('MDC UTILITIES', 'government_excluded', TRUE),
('MEDICAID', 'government_excluded', TRUE),
('MEDICARE', 'government_excluded', TRUE),
('MEDICARE REIMBURSEMENT', 'government_excluded', TRUE),
('MEDTRONIC FINANCE', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;