INSERT INTO exclusion_keywords (keyword, reason, is_active) VALUES
('ERICSSON CREDIT', 'government_excluded', TRUE),
('ESA PAYROLL', 'government_excluded', TRUE),
('ESCROW', 'government_excluded', TRUE),
('EVERSOURCE', 'government_excluded', TRUE),
('EXCELLUS', 'government_excluded', TRUE),
('EXCISE', 'government_excluded', TRUE),
('EXPENSE REIMBURSEMENT', 'government_excluded', TRUE),
('EXPRESS SCRIPTS', 'government_excluded', TRUE),
('F&B', 'government_excluded', TRUE),
('family trust', 'government_excluded', TRUE),
('FANNIE MAE', 'government_excluded', TRUE),
('FARM BUREAU', 'government_excluded', TRUE),
('FARM CREDIT', 'government_excluded', TRUE),
('farmers and merchants bank', 'government_excluded', TRUE),
('FARMERS INSURANCE', 'government_excluded', TRUE),
('FBI', 'government_excluded', TRUE),
('FDIC', 'government_excluded', TRUE),
('FEDERAL', 'government_excluded', TRUE),
('FEDERAL EXPRESS FREIGHT', 'government_excluded', TRUE),
('FEDERAL RESERVE', 'government_excluded', TRUE),
('FEDEX FREIGHT PAYMENT', 'government_excluded', TRUE),
('FEMA', 'government_excluded', TRUE),
('FIDELITY', 'government_excluded', TRUE),
('FIDUCIARY', 'government_excluded', TRUE),
('FIFTH THIRD', 'government_excluded', TRUE),
('FINANCE', 'government_excluded', TRUE),
('FINANCE AND INSURANCE', 'government_excluded', TRUE),
('FINANCIAL', 'government_excluded', TRUE),
('FINANCIAL ENFORCEMENT', 'government_excluded', TRUE),
('FIRM', 'government_excluded', TRUE),
('first american title', 'government_excluded', TRUE),
('FISCAL SERVICE', 'government_excluded', TRUE),
('FISCAL SERVICES', 'government_excluded', TRUE),
('FLEET', 'government_excluded', TRUE),
('FLORIDA POWER & LIGHT', 'government_excluded', TRUE),
('FORESTRY', 'government_excluded', TRUE),
('FORTIS', 'government_excluded', TRUE),
('foundation', 'government_excluded', TRUE),
('FRANCHISE TAX', 'government_excluded', TRUE),
('FRONTIER COMMUNICATIONS', 'government_excluded', TRUE),
('FUND', 'government_excluded', TRUE),
('FUNDING', 'government_excluded', TRUE),
('FUNDS', 'government_excluded', TRUE),
('FUTURES', 'government_excluded', TRUE),
('G&K SERVICES', 'government_excluded', TRUE),
('GALLAGHER BENEFIT', 'government_excluded', TRUE),
('GAMING COMMISSION', 'government_excluded', TRUE),
('GAS', 'government_excluded', TRUE),
('GAS CO', 'government_excluded', TRUE),
('GAS COMPANY', 'government_excluded', TRUE)
ON CONFLICT (keyword) DO UPDATE SET is_active = TRUE;