
name: Update Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Generate API documentation
      run: |
        echo "Generating updated documentation..."
        # Add any doc generation scripts here
        
    - name: Update README badges
      run: |
        # Update any dynamic badges or stats in README
        echo "Documentation updated on $(date)" >> docs/LAST_UPDATED.md
    
    - name: Commit documentation changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/ README.md
        git diff --staged --quiet || git commit -m "Auto-update documentation [skip ci]"
        git push
      if: github.event_name == 'push'
